services:
  - type: web
    name: kasirpinter-go
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8000
      - key: DB_HOST
        sync: false
      - key: DB_HOST_UNPOOLED
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_ROLE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
