package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"re-kasirpinter-go/graph/input"
)

// Password is the resolver for the password field.
func (r *updateUserInputResolver) Password(ctx context.Context, obj *input.UpdateUserInput, data *string) error {
	obj.Password = data
	return nil
}

// UpdateUserInput returns UpdateUserInputResolver implementation.
func (r *Resolver) UpdateUserInput() UpdateUserInputResolver { return &updateUserInputResolver{r} }

type updateUserInputResolver struct{ *Resolver }
