package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"re-kasirpinter-go/graph/input"
	"re-kasirpinter-go/graph/model"
	"time"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input input.LoginInput) (*model.AuthResponse, error) {
	// Find user by email
	var userDB model.UserDB
	result := r.DB.Where("email = ? AND is_active = ?", input.Email, true).First(&userDB)
	if result.Error != nil {
		return &model.AuthResponse{
			Code:    401,
			Success: false,
			Message: "invalid email or password",
		}, nil
	}

	// Check password
	if !checkPassword(input.Password, userDB.Password) {
		return &model.AuthResponse{
			Code:    401,
			Success: false,
			Message: "invalid email or password",
		}, nil
	}

	// Get user role
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Generate JWT token
	roleName := ""
	if userRole.ID > 0 {
		roleName = userRole.Name
	}

	secureID := ""
	if userDB.SecureID != nil {
		secureID = *userDB.SecureID
	}

	token, err := generateJWT(userDB.ID, userDB.Email, roleName, secureID, "login")
	if err != nil {
		return &model.AuthResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to generate token: %v", err),
		}, nil
	}

	// Convert DB model to GraphQL model using mapper
	var userRoleDB *model.UserRoleDB
	if userRole.ID > 0 {
		userRoleDB = &userRole
	}
	user := toGraphQLUser(userDB, userRoleDB)

	return &model.AuthResponse{
		Code:    200,
		Success: true,
		Message: "login successful",
		Data: &model.AuthData{
			Token: token,
			User:  user,
		},
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input input.CreateUserInput) (*model.CreateUserResponse, error) {
	// Generate secure_id (UUID)
	secureID, err := generateRandomString(16)
	if err != nil {
		return &model.CreateUserResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to generate secure_id: %v", err),
		}, nil
	}

	// Hash password
	hashedPassword, err := hashPassword(input.Password)
	if err != nil {
		return &model.CreateUserResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to hash password: %v", err),
		}, nil
	}

	// Create user DB model
	userDB := model.UserDB{
		SecureID: &secureID,
		Name:     input.Name,
		Email:    input.Email,
		Address:  input.Address,
		Phone:    input.Phone,
		Password: hashedPassword,
		IsActive: true,
		RoleID:   input.RoleID,
	}

	// Save to database
	result := r.DB.Create(&userDB)
	if result.Error != nil {
		return &model.CreateUserResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to create user: %v", result.Error),
		}, nil
	}

	// Get user role if exists
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Convert DB model to GraphQL model using mapper
	var userRoleDB *model.UserRoleDB
	if userRole.ID > 0 {
		userRoleDB = &userRole
	}
	user := toGraphQLUser(userDB, userRoleDB)

	return &model.CreateUserResponse{
		Code:    201,
		Success: true,
		Message: "user created successfully",
		Data:    user,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input input.UpdateUserInput) (*model.UpdateUserResponse, error) {
	// Find user by secure_id
	var userDB model.UserDB
	result := r.DB.Where("secure_id = ?", id).First(&userDB)
	if result.Error != nil {
		return &model.UpdateUserResponse{
			Code:    404,
			Success: false,
			Message: "user not found",
		}, nil
	}

	// Update fields if provided
	if input.Name != nil {
		userDB.Name = *input.Name
	}
	if input.Email != nil {
		userDB.Email = *input.Email
	}
	if input.Address != nil {
		userDB.Address = *input.Address
	}
	if input.Phone != nil {
		userDB.Phone = *input.Phone
	}
	if input.Avatar != nil {
		userDB.Avatar = input.Avatar
	}
	if input.IsActive != nil {
		userDB.IsActive = *input.IsActive
	}
	if input.RoleID != nil {
		userDB.RoleID = input.RoleID
	}

	// Save to database
	result = r.DB.Save(&userDB)
	if result.Error != nil {
		return &model.UpdateUserResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to update user: %v", result.Error),
		}, nil
	}

	// Get user role if exists
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Convert DB model to GraphQL model using mapper
	var userRoleDB *model.UserRoleDB
	if userRole.ID > 0 {
		userRoleDB = &userRole
	}
	user := toGraphQLUser(userDB, userRoleDB)

	return &model.UpdateUserResponse{
		Code:    200,
		Success: true,
		Message: "user updated successfully",
		Data:    user,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.DeleteUserResponse, error) {
	// Find user by secure_id
	var userDB model.UserDB
	result := r.DB.Where("secure_id = ?", id).First(&userDB)
	if result.Error != nil {
		return &model.DeleteUserResponse{
			Code:    404,
			Success: false,
			Message: "user not found",
		}, nil
	}

	// Soft delete by setting deleted_at and is_active
	now := time.Now()
	userDB.DeletedAt = &now
	userDB.IsActive = false

	// Save to database
	result = r.DB.Save(&userDB)
	if result.Error != nil {
		return &model.DeleteUserResponse{
			Code:    500,
			Success: false,
			Message: fmt.Sprintf("failed to delete user: %v", result.Error),
		}, nil
	}

	// Get user role if exists
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Convert DB model to GraphQL model using mapper
	var userRoleDB *model.UserRoleDB
	if userRole.ID > 0 {
		userRoleDB = &userRole
	}
	user := toGraphQLUser(userDB, userRoleDB)

	return &model.DeleteUserResponse{
		Code:    200,
		Success: true,
		Message: "user deleted successfully",
		Data:    user,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *model.PaginationInput) (*model.UsersResponse, error) {
	// Set default values
	defaultLimit := int32(10)
	defaultPage := int32(1)
	defaultSortBy := "created_at,desc"

	if pagination != nil {
		if pagination.Limit != nil && *pagination.Limit > 0 {
			defaultLimit = *pagination.Limit
		}
		if pagination.Page != nil && *pagination.Page > 0 {
			defaultPage = *pagination.Page
		}
		if pagination.SortBy != nil && *pagination.SortBy != "" {
			defaultSortBy = *pagination.SortBy
		}
	}

	// Parse sortBy (format: "field,direction")
	// Convert "created_at,desc" to "created_at desc"
	sortBy := defaultSortBy
	if len(sortBy) > 0 {
		// Replace comma with space for GORM
		sortBy = defaultSortBy
		for i := 0; i < len(sortBy); i++ {
			if sortBy[i] == ',' {
				sortBy = sortBy[:i] + " " + sortBy[i+1:]
				break
			}
		}
	}

	// Calculate offset
	offset := (defaultPage - 1) * defaultLimit

	// Get total count
	var total int64
	countResult := r.DB.Model(&model.UserDB{}).Count(&total)
	if countResult.Error != nil {
		return nil, countResult.Error
	}

	// Query users with pagination
	var usersDB []model.UserDB
	query := r.DB.Order(sortBy).Limit(int(defaultLimit)).Offset(int(offset))
	result := query.Find(&usersDB)
	if result.Error != nil {
		return nil, result.Error
	}

	// Calculate pagination metadata
	totalPages := int32(0)
	if total > 0 {
		totalPages = (int32(total) + defaultLimit - 1) / defaultLimit
	}

	hasNextPage := defaultPage < totalPages
	hasPreviousPage := defaultPage > 1

	startItem := int32(0)
	if total > 0 {
		startItem = offset + 1
	}

	endItem := int32(0)
	if total > 0 {
		endItem = offset + int32(len(usersDB))
		if endItem > int32(total) {
			endItem = int32(total)
		}
	}

	// Convert DB models to GraphQL models
	users := make([]*model.User, len(usersDB))
	for i, userDB := range usersDB {
		// Get user role if exists
		var userRoleDB *model.UserRoleDB
		if userDB.RoleID != nil {
			var userRole model.UserRoleDB
			r.DB.First(&userRole, *userDB.RoleID)
			if userRole.ID > 0 {
				userRoleDB = &userRole
			}
		}

		users[i] = toGraphQLUser(userDB, userRoleDB)
	}

	// Build pagination info
	pageInfo := &model.PageInfo{
		CurrentPage:     defaultPage,
		PerPage:         defaultLimit,
		TotalItems:      int32(total),
		TotalPages:      totalPages,
		HasNextPage:     hasNextPage,
		HasPreviousPage: hasPreviousPage,
	}

	if total > 0 {
		pageInfo.StartItem = &startItem
		pageInfo.EndItem = &endItem
	}

	return &model.UsersResponse{
		Data:       users,
		Pagination: pageInfo,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, secureID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
