package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"re-kasirpinter-go/graph/input"
	"re-kasirpinter-go/graph/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input input.LoginInput) (*model.AuthResponse, error) {
	// Find user by email
	var userDB model.UserDB
	result := r.DB.Where("email = ? AND is_active = ?", input.Email, true).First(&userDB)
	if result.Error != nil {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Check password
	if !checkPassword(input.Password, userDB.Password) {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Get user role
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Generate JWT token
	roleName := ""
	if userRole.ID > 0 {
		roleName = userRole.Name
	}

	secureID := ""
	if userDB.SecureID != nil {
		secureID = *userDB.SecureID
	}

	token, err := generateJWT(userDB.ID, userDB.Email, roleName, secureID, "login")
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %v", err)
	}

	// Convert DB model to GraphQL model
	user := &model.User{
		ID:        userDB.ID,
		SecureID:  userDB.SecureID,
		Name:      userDB.Name,
		Email:     userDB.Email,
		Address:   userDB.Address,
		Phone:     userDB.Phone,
		Avatar:    userDB.Avatar,
		IsActive:  userDB.IsActive,
		DeletedAt: userDB.DeletedAt,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	if userRole.ID > 0 {
		user.Role = &model.UserRole{
			ID:          userRole.ID,
			Name:        userRole.Name,
			IsActive:    userRole.IsActive,
			CreatedAt:   userRole.CreatedAt,
			CreatedBy:   userRole.CreatedBy,
			UpdatedAt:   userRole.UpdatedAt,
			UpdatedBy:   userRole.UpdatedBy,
			DeletedAt:   userRole.DeletedAt,
			DeletedBy:   userRole.DeletedBy,
			Permissions: nil, // Can be populated if needed
		}
	}

	return &model.AuthResponse{
		Token: token,
		User:  user,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input input.CreateUserInput) (*model.User, error) {
	// Generate secure_id (UUID)
	secureID, err := generateRandomString(16)
	if err != nil {
		return nil, fmt.Errorf("failed to generate secure_id: %v", err)
	}

	// Hash password
	hashedPassword, err := hashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}

	// Create user DB model
	userDB := model.UserDB{
		SecureID: &secureID,
		Name:     input.Name,
		Email:    input.Email,
		Address:  input.Address,
		Phone:    input.Phone,
		Password: hashedPassword,
		IsActive: true,
		RoleID:   input.RoleID,
	}

	// Save to database
	result := r.DB.Create(&userDB)
	if result.Error != nil {
		return nil, fmt.Errorf("failed to create user: %v", result.Error)
	}

	// Get user role if exists
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Convert DB model to GraphQL model
	user := &model.User{
		ID:        userDB.ID,
		SecureID:  userDB.SecureID,
		Name:      userDB.Name,
		Email:     userDB.Email,
		Address:   userDB.Address,
		Phone:     userDB.Phone,
		Avatar:    userDB.Avatar,
		IsActive:  userDB.IsActive,
		DeletedAt: userDB.DeletedAt,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	if userRole.ID > 0 {
		user.Role = &model.UserRole{
			ID:          userRole.ID,
			Name:        userRole.Name,
			IsActive:    userRole.IsActive,
			CreatedAt:   userRole.CreatedAt,
			CreatedBy:   userRole.CreatedBy,
			UpdatedAt:   userRole.UpdatedAt,
			UpdatedBy:   userRole.UpdatedBy,
			DeletedAt:   userRole.DeletedAt,
			DeletedBy:   userRole.DeletedBy,
			Permissions: nil,
		}
	}

	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input input.UpdateUserInput) (*model.User, error) {
	// Find user by secure_id
	var userDB model.UserDB
	result := r.DB.Where("secure_id = ?", id).First(&userDB)
	if result.Error != nil {
		return nil, fmt.Errorf("user not found")
	}

	// Update fields if provided
	if input.Name != nil {
		userDB.Name = *input.Name
	}
	if input.Email != nil {
		userDB.Email = *input.Email
	}
	if input.Address != nil {
		userDB.Address = *input.Address
	}
	if input.Phone != nil {
		userDB.Phone = *input.Phone
	}
	if input.Avatar != nil {
		userDB.Avatar = input.Avatar
	}
	if input.IsActive != nil {
		userDB.IsActive = *input.IsActive
	}
	if input.RoleID != nil {
		userDB.RoleID = input.RoleID
	}

	// Save to database
	result = r.DB.Save(&userDB)
	if result.Error != nil {
		return nil, fmt.Errorf("failed to update user: %v", result.Error)
	}

	// Get user role if exists
	var userRole model.UserRoleDB
	if userDB.RoleID != nil {
		r.DB.First(&userRole, *userDB.RoleID)
	}

	// Convert DB model to GraphQL model
	user := &model.User{
		ID:        userDB.ID,
		SecureID:  userDB.SecureID,
		Name:      userDB.Name,
		Email:     userDB.Email,
		Address:   userDB.Address,
		Phone:     userDB.Phone,
		Avatar:    userDB.Avatar,
		IsActive:  userDB.IsActive,
		DeletedAt: userDB.DeletedAt,
		CreatedAt: userDB.CreatedAt,
		UpdatedAt: userDB.UpdatedAt,
	}

	if userRole.ID > 0 {
		user.Role = &model.UserRole{
			ID:          userRole.ID,
			Name:        userRole.Name,
			IsActive:    userRole.IsActive,
			CreatedAt:   userRole.CreatedAt,
			CreatedBy:   userRole.CreatedBy,
			UpdatedAt:   userRole.UpdatedAt,
			UpdatedBy:   userRole.UpdatedBy,
			DeletedAt:   userRole.DeletedAt,
			DeletedBy:   userRole.DeletedBy,
			Permissions: nil,
		}
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, secureID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
