// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthData struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CheckDiscountData struct {
	Type     DiscountType `json:"type"`
	Value    float64      `json:"value"`
	MaxValue float64      `json:"max_value"`
	MinOrder float64      `json:"min_order"`
}

type CheckDiscountResponse struct {
	Code    int32              `json:"code"`
	Success bool               `json:"success"`
	Message string             `json:"message"`
	Data    *CheckDiscountData `json:"data,omitempty"`
}

type CreateDiscountInput struct {
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Icon        *string      `json:"icon,omitempty"`
	Code        *string      `json:"code,omitempty"`
	Type        DiscountType `json:"type"`
	Value       float64      `json:"value"`
	MaxValue    *int32       `json:"max_value,omitempty"`
	MinOrder    *int32       `json:"min_order,omitempty"`
	Quota       *int32       `json:"quota,omitempty"`
	StartAt     *time.Time   `json:"start_at,omitempty"`
	EndAt       *time.Time   `json:"end_at,omitempty"`
	IsActive    bool         `json:"is_active"`
}

type CreateDiscountResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *Discount `json:"data,omitempty"`
}

type CreateIngredientCategoryInput struct {
	Name        string  `json:"name"`
	Unit        string  `json:"unit"`
	ConvertUnit *string `json:"convert_unit,omitempty"`
	IsActive    bool    `json:"is_active"`
}

type CreateIngredientCategoryResponse struct {
	Code    int32               `json:"code"`
	Success bool                `json:"success"`
	Message string              `json:"message"`
	Data    *IngredientCategory `json:"data,omitempty"`
}

type CreateIngredientInput struct {
	Name       string `json:"name"`
	CategoryID *int64 `json:"category_id,omitempty"`
	IsActive   bool   `json:"is_active"`
}

type CreateIngredientResponse struct {
	Code    int32       `json:"code"`
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *Ingredient `json:"data,omitempty"`
}

type CreateIngredientStockInput struct {
	Code         *string             `json:"code,omitempty"`
	Qty          float64             `json:"qty"`
	Type         IngredientStockType `json:"type"`
	Capital      float64             `json:"capital"`
	Message      *string             `json:"message,omitempty"`
	Image        *string             `json:"image,omitempty"`
	IngredientID int64               `json:"ingredient_id"`
}

type CreateIngredientStockResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *IngredientStock `json:"data,omitempty"`
}

type CreateOtpInput struct {
	Email string `json:"email"`
	Type  string `json:"type"`
	Retry *bool  `json:"retry,omitempty"`
}

type CreateOtpResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateProductCategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ParentID    *int64  `json:"parent_id,omitempty"`
	IsActive    bool    `json:"is_active"`
}

type CreateProductCategoryResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *ProductCategory `json:"data,omitempty"`
}

type CreateProductIngredientInput struct {
	VariantID       int64   `json:"variant_id"`
	IngredientID    int64   `json:"ingredient_id"`
	IngredientValue float64 `json:"ingredient_value"`
	Unit            string  `json:"unit"`
}

type CreateProductIngredientResponse struct {
	Code    int32                `json:"code"`
	Success bool                 `json:"success"`
	Message string               `json:"message"`
	Data    []*ProductIngredient `json:"data,omitempty"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Image       *string `json:"image,omitempty"`
	CategoryID  *int64  `json:"category_id,omitempty"`
	Description *string `json:"description,omitempty"`
	IsActive    bool    `json:"is_active"`
}

type CreateProductResponse struct {
	Code    int32    `json:"code"`
	Success bool     `json:"success"`
	Message string   `json:"message"`
	Data    *Product `json:"data,omitempty"`
}

type CreateProductVariantInput struct {
	Image         *string  `json:"image,omitempty"`
	ProductID     int64    `json:"product_id"`
	Name          string   `json:"name"`
	Price         float64  `json:"price"`
	PriceOriginal *float64 `json:"price_original,omitempty"`
	IsUnlimited   bool     `json:"is_unlimited"`
	IsActive      bool     `json:"is_active"`
}

type CreateProductVariantResponse struct {
	Code    int32           `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Data    *ProductVariant `json:"data,omitempty"`
}

type CreateRoleInput struct {
	Name          string   `json:"name"`
	Status        bool     `json:"status"`
	PermissionIds []*int64 `json:"permission_ids,omitempty"`
}

type CreateRoleResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *UserRole `json:"data,omitempty"`
}

type CreateUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type DeleteDiscountResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *Discount `json:"data,omitempty"`
}

type DeleteIngredientCategoryResponse struct {
	Code    int32               `json:"code"`
	Success bool                `json:"success"`
	Message string              `json:"message"`
	Data    *IngredientCategory `json:"data,omitempty"`
}

type DeleteIngredientResponse struct {
	Code    int32       `json:"code"`
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *Ingredient `json:"data,omitempty"`
}

type DeleteIngredientStockResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *IngredientStock `json:"data,omitempty"`
}

type DeleteProductCategoryResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *ProductCategory `json:"data,omitempty"`
}

type DeleteProductIngredientResponse struct {
	Code    int32                `json:"code"`
	Success bool                 `json:"success"`
	Message string               `json:"message"`
	Data    []*ProductIngredient `json:"data,omitempty"`
}

type DeleteProductResponse struct {
	Code    int32    `json:"code"`
	Success bool     `json:"success"`
	Message string   `json:"message"`
	Data    *Product `json:"data,omitempty"`
}

type DeleteProductVariantResponse struct {
	Code    int32           `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Data    *ProductVariant `json:"data,omitempty"`
}

type DeleteRoleResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *UserRole `json:"data,omitempty"`
}

type DeleteUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type Discount struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Icon        *string      `json:"icon,omitempty"`
	Code        *string      `json:"code,omitempty"`
	Type        DiscountType `json:"type"`
	Value       float64      `json:"value"`
	MaxValue    *int32       `json:"max_value,omitempty"`
	MinOrder    *int32       `json:"min_order,omitempty"`
	Quota       *int32       `json:"quota,omitempty"`
	StartAt     *time.Time   `json:"start_at,omitempty"`
	EndAt       *time.Time   `json:"end_at,omitempty"`
	IsActive    bool         `json:"is_active"`
	DeletedAt   *time.Time   `json:"deleted_at,omitempty"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type DiscountResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *Discount `json:"data,omitempty"`
}

type DiscountsResponse struct {
	Code       int32       `json:"code"`
	Success    bool        `json:"success"`
	Message    string      `json:"message"`
	Data       []*Discount `json:"data"`
	Pagination *PageInfo   `json:"pagination,omitempty"`
}

type Ingredient struct {
	ID          int64               `json:"id"`
	Name        string              `json:"name"`
	CategoryID  *int64              `json:"category_id,omitempty"`
	Category    *IngredientCategory `json:"category,omitempty"`
	IsActive    bool                `json:"is_active"`
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	UpdatedAt   time.Time           `json:"updated_at"`
	Stocks      []*IngredientStock  `json:"stocks"`
	TotalStocks float64             `json:"total_stocks"`
}

type IngredientCategoriesResponse struct {
	Code       int32                 `json:"code"`
	Success    bool                  `json:"success"`
	Message    string                `json:"message"`
	Data       []*IngredientCategory `json:"data"`
	Pagination *PageInfo             `json:"pagination,omitempty"`
}

type IngredientCategory struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Unit        string     `json:"unit"`
	ConvertUnit *string    `json:"convert_unit,omitempty"`
	IsActive    bool       `json:"is_active"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type IngredientCategoryResponse struct {
	Code    int32               `json:"code"`
	Success bool                `json:"success"`
	Message string              `json:"message"`
	Data    *IngredientCategory `json:"data,omitempty"`
}

type IngredientResponse struct {
	Code    int32       `json:"code"`
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *Ingredient `json:"data,omitempty"`
}

type IngredientStock struct {
	ID           int64               `json:"id"`
	Code         *string             `json:"code,omitempty"`
	Qty          float64             `json:"qty"`
	Type         IngredientStockType `json:"type"`
	Capital      float64             `json:"capital"`
	CapitalItem  float64             `json:"capital_item"`
	Message      *string             `json:"message,omitempty"`
	Image        *string             `json:"image,omitempty"`
	DeletedAt    *time.Time          `json:"deleted_at,omitempty"`
	CreatedAt    time.Time           `json:"created_at"`
	UpdatedAt    time.Time           `json:"updated_at"`
	IngredientID int64               `json:"ingredient_id"`
	Ingredient   *Ingredient         `json:"ingredient,omitempty"`
}

type IngredientStockResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *IngredientStock `json:"data,omitempty"`
}

type IngredientStocksResponse struct {
	Code           int32              `json:"code"`
	Success        bool               `json:"success"`
	Message        string             `json:"message"`
	IngredientName *string            `json:"ingredient_name,omitempty"`
	TotalStocks    *float64           `json:"total_stocks,omitempty"`
	Unit           *string            `json:"unit,omitempty"`
	ConvertUnit    *string            `json:"convert_unit,omitempty"`
	Data           []*IngredientStock `json:"data"`
	Pagination     *PageInfo          `json:"pagination,omitempty"`
}

type IngredientsResponse struct {
	Code       int32         `json:"code"`
	Success    bool          `json:"success"`
	Message    string        `json:"message"`
	Data       []*Ingredient `json:"data"`
	Pagination *PageInfo     `json:"pagination,omitempty"`
}

type LogoutResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type NewPasswordInput struct {
	Password string `json:"password"`
}

type NewPasswordResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type PageInfo struct {
	CurrentPage     int32  `json:"current_page"`
	PerPage         int32  `json:"per_page"`
	TotalItems      int32  `json:"total_items"`
	TotalPages      int32  `json:"total_pages"`
	HasNextPage     bool   `json:"has_next_page"`
	HasPreviousPage bool   `json:"has_previous_page"`
	StartItem       *int32 `json:"start_item,omitempty"`
	EndItem         *int32 `json:"end_item,omitempty"`
}

type PaginationInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Page   *int32  `json:"page,omitempty"`
	SortBy *string `json:"sortBy,omitempty"`
}

type PermissionsResponse struct {
	Code    int32             `json:"code"`
	Success bool              `json:"success"`
	Message string            `json:"message"`
	Data    []*UserPermission `json:"data"`
}

type Product struct {
	ID          int64             `json:"id"`
	SecureID    *string           `json:"secure_id,omitempty"`
	Name        string            `json:"name"`
	Image       *string           `json:"image,omitempty"`
	CategoryID  *int64            `json:"category_id,omitempty"`
	Category    *ProductCategory  `json:"category,omitempty"`
	Description *string           `json:"description,omitempty"`
	IsAvailable bool              `json:"is_available"`
	IsActive    bool              `json:"is_active"`
	DeletedAt   *time.Time        `json:"deleted_at,omitempty"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	Variants    []*ProductVariant `json:"variants"`
}

type ProductCategoriesResponse struct {
	Code       int32              `json:"code"`
	Success    bool               `json:"success"`
	Message    string             `json:"message"`
	Data       []*ProductCategory `json:"data"`
	Pagination *PageInfo          `json:"pagination,omitempty"`
}

type ProductCategory struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description,omitempty"`
	ParentID    *int64             `json:"parent_id,omitempty"`
	Parent      *ProductCategory   `json:"parent,omitempty"`
	Children    []*ProductCategory `json:"children"`
	IsActive    bool               `json:"is_active"`
	DeletedAt   *time.Time         `json:"deleted_at,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type ProductCategoryResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *ProductCategory `json:"data,omitempty"`
}

type ProductIngredient struct {
	ID              int64           `json:"id"`
	VariantID       int64           `json:"variant_id"`
	Variant         *ProductVariant `json:"variant,omitempty"`
	IngredientID    int64           `json:"ingredient_id"`
	Ingredient      *Ingredient     `json:"ingredient,omitempty"`
	IngredientValue float64         `json:"ingredient_value"`
	Unit            string          `json:"unit"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ProductIngredientResponse struct {
	Code    int32              `json:"code"`
	Success bool               `json:"success"`
	Message string             `json:"message"`
	Data    *ProductIngredient `json:"data,omitempty"`
}

type ProductIngredientsResponse struct {
	Code       int32                `json:"code"`
	Success    bool                 `json:"success"`
	Message    string               `json:"message"`
	Data       []*ProductIngredient `json:"data"`
	Pagination *PageInfo            `json:"pagination,omitempty"`
}

type ProductResponse struct {
	Code    int32    `json:"code"`
	Success bool     `json:"success"`
	Message string   `json:"message"`
	Data    *Product `json:"data,omitempty"`
}

type ProductVariant struct {
	ID             int64                `json:"id"`
	Image          *string              `json:"image,omitempty"`
	ProductID      int64                `json:"product_id"`
	Product        *Product             `json:"product,omitempty"`
	Name           string               `json:"name"`
	Price          float64              `json:"price"`
	PriceOriginal  *float64             `json:"price_original,omitempty"`
	Ingredients    []*ProductIngredient `json:"ingredients"`
	AvailableStock float64              `json:"available_stock"`
	IsUnlimited    bool                 `json:"is_unlimited"`
	IsActive       bool                 `json:"is_active"`
	DeletedAt      *time.Time           `json:"deleted_at,omitempty"`
	CreatedAt      time.Time            `json:"created_at"`
	UpdatedAt      time.Time            `json:"updated_at"`
}

type ProductVariantResponse struct {
	Code    int32           `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Data    *ProductVariant `json:"data,omitempty"`
}

type ProductVariantsResponse struct {
	Code       int32             `json:"code"`
	Success    bool              `json:"success"`
	Message    string            `json:"message"`
	Data       []*ProductVariant `json:"data"`
	Pagination *PageInfo         `json:"pagination,omitempty"`
}

type ProductsResponse struct {
	Code       int32      `json:"code"`
	Success    bool       `json:"success"`
	Message    string     `json:"message"`
	Data       []*Product `json:"data"`
	Pagination *PageInfo  `json:"pagination,omitempty"`
}

type Query struct {
}

type RoleResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *UserRole `json:"data,omitempty"`
}

type RolesResponse struct {
	Code    int32       `json:"code"`
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    []*UserRole `json:"data"`
}

type UpdateDiscountInput struct {
	Name        *string       `json:"name,omitempty"`
	Description *string       `json:"description,omitempty"`
	Icon        *string       `json:"icon,omitempty"`
	Code        *string       `json:"code,omitempty"`
	Type        *DiscountType `json:"type,omitempty"`
	Value       *float64      `json:"value,omitempty"`
	MaxValue    *int32        `json:"max_value,omitempty"`
	MinOrder    *int32        `json:"min_order,omitempty"`
	Quota       *int32        `json:"quota,omitempty"`
	StartAt     *time.Time    `json:"start_at,omitempty"`
	EndAt       *time.Time    `json:"end_at,omitempty"`
	IsActive    *bool         `json:"is_active,omitempty"`
}

type UpdateDiscountResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *Discount `json:"data,omitempty"`
}

type UpdateIngredientCategoryInput struct {
	Name        string  `json:"name"`
	Unit        string  `json:"unit"`
	ConvertUnit *string `json:"convert_unit,omitempty"`
	IsActive    bool    `json:"is_active"`
}

type UpdateIngredientCategoryResponse struct {
	Code    int32               `json:"code"`
	Success bool                `json:"success"`
	Message string              `json:"message"`
	Data    *IngredientCategory `json:"data,omitempty"`
}

type UpdateIngredientInput struct {
	Name       *string `json:"name,omitempty"`
	CategoryID *int64  `json:"category_id,omitempty"`
	IsActive   *bool   `json:"is_active,omitempty"`
}

type UpdateIngredientResponse struct {
	Code    int32       `json:"code"`
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    *Ingredient `json:"data,omitempty"`
}

type UpdateIngredientStockInput struct {
	Code         *string              `json:"code,omitempty"`
	Qty          *float64             `json:"qty,omitempty"`
	Type         *IngredientStockType `json:"type,omitempty"`
	Capital      *float64             `json:"capital,omitempty"`
	Message      *string              `json:"message,omitempty"`
	Image        *string              `json:"image,omitempty"`
	IngredientID *int64               `json:"ingredient_id,omitempty"`
}

type UpdateIngredientStockResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *IngredientStock `json:"data,omitempty"`
}

type UpdateProductCategoryInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ParentID    *int64  `json:"parent_id,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type UpdateProductCategoryResponse struct {
	Code    int32            `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Data    *ProductCategory `json:"data,omitempty"`
}

type UpdateProductIngredientInput struct {
	IngredientValue *float64 `json:"ingredient_value,omitempty"`
	Unit            *string  `json:"unit,omitempty"`
}

type UpdateProductIngredientResponse struct {
	Code    int32              `json:"code"`
	Success bool               `json:"success"`
	Message string             `json:"message"`
	Data    *ProductIngredient `json:"data,omitempty"`
}

type UpdateProductInput struct {
	Name        *string `json:"name,omitempty"`
	Image       *string `json:"image,omitempty"`
	CategoryID  *int64  `json:"category_id,omitempty"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"is_active,omitempty"`
}

type UpdateProductResponse struct {
	Code    int32    `json:"code"`
	Success bool     `json:"success"`
	Message string   `json:"message"`
	Data    *Product `json:"data,omitempty"`
}

type UpdateProductVariantInput struct {
	Image         *string  `json:"image,omitempty"`
	Name          *string  `json:"name,omitempty"`
	Price         *float64 `json:"price,omitempty"`
	PriceOriginal *float64 `json:"price_original,omitempty"`
	IsUnlimited   *bool    `json:"is_unlimited,omitempty"`
	IsActive      *bool    `json:"is_active,omitempty"`
}

type UpdateProductVariantResponse struct {
	Code    int32           `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Data    *ProductVariant `json:"data,omitempty"`
}

type UpdateRoleInput struct {
	Name          string   `json:"name"`
	Status        bool     `json:"status"`
	PermissionIds []*int64 `json:"permission_ids,omitempty"`
}

type UpdateRoleResponse struct {
	Code    int32     `json:"code"`
	Success bool      `json:"success"`
	Message string    `json:"message"`
	Data    *UserRole `json:"data,omitempty"`
}

type UpdateUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type User struct {
	ID        int32      `json:"id"`
	SecureID  *string    `json:"secure_id,omitempty"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Address   string     `json:"address"`
	Phone     string     `json:"phone"`
	Avatar    *string    `json:"avatar,omitempty"`
	IsActive  bool       `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	Role      *UserRole  `json:"role,omitempty"`
}

type UserPermission struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type UserRole struct {
	ID          int64             `json:"id"`
	Name        string            `json:"name"`
	IsActive    bool              `json:"is_active"`
	CreatedAt   time.Time         `json:"created_at"`
	CreatedBy   *string           `json:"created_by,omitempty"`
	UpdatedAt   time.Time         `json:"updated_at"`
	UpdatedBy   *string           `json:"updated_by,omitempty"`
	DeletedAt   *time.Time        `json:"deleted_at,omitempty"`
	DeletedBy   *string           `json:"deleted_by,omitempty"`
	Permissions []*UserPermission `json:"permissions"`
}

type UserRolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type UsersResponse struct {
	Code       int32     `json:"code"`
	Success    bool      `json:"success"`
	Message    string    `json:"message"`
	Data       []*User   `json:"data"`
	Pagination *PageInfo `json:"pagination"`
}

type VerifyOtpInput struct {
	Email string `json:"email"`
	Code  string `json:"code"`
	Type  string `json:"type"`
}

type VerifyOtpResponse struct {
	Code    int32   `json:"code"`
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Token   *string `json:"token,omitempty"`
}
