// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthData struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateOtpInput struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

type CreateOtpResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type DeleteUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	CurrentPage     int32  `json:"current_page"`
	PerPage         int32  `json:"per_page"`
	TotalItems      int32  `json:"total_items"`
	TotalPages      int32  `json:"total_pages"`
	HasNextPage     bool   `json:"has_next_page"`
	HasPreviousPage bool   `json:"has_previous_page"`
	StartItem       *int32 `json:"start_item,omitempty"`
	EndItem         *int32 `json:"end_item,omitempty"`
}

type PaginationInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Page   *int32  `json:"page,omitempty"`
	SortBy *string `json:"sortBy,omitempty"`
}

type Query struct {
}

type UpdateUserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type User struct {
	ID        int32      `json:"id"`
	SecureID  *string    `json:"secure_id,omitempty"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Address   string     `json:"address"`
	Phone     string     `json:"phone"`
	Avatar    *string    `json:"avatar,omitempty"`
	IsActive  bool       `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	Role      *UserRole  `json:"role,omitempty"`
}

type UserPermission struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UserResponse struct {
	Code    int32  `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type UserRole struct {
	ID          int64             `json:"id"`
	Name        string            `json:"name"`
	IsActive    bool              `json:"is_active"`
	CreatedAt   time.Time         `json:"created_at"`
	CreatedBy   *string           `json:"created_by,omitempty"`
	UpdatedAt   time.Time         `json:"updated_at"`
	UpdatedBy   *string           `json:"updated_by,omitempty"`
	DeletedAt   *time.Time        `json:"deleted_at,omitempty"`
	DeletedBy   *string           `json:"deleted_by,omitempty"`
	Permissions []*UserPermission `json:"permissions"`
}

type UserRolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type UsersResponse struct {
	Code       int32     `json:"code"`
	Success    bool      `json:"success"`
	Message    string    `json:"message"`
	Data       []*User   `json:"data"`
	Pagination *PageInfo `json:"pagination"`
}

type VerifyOtpInput struct {
	Email string `json:"email"`
	Code  string `json:"code"`
	Type  string `json:"type"`
}

type VerifyOtpResponse struct {
	Code    int32   `json:"code"`
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Token   *string `json:"token,omitempty"`
}
